---
- hosts: all
  gather_facts: no
  become: no
  roles:
    - Ubuntu22CIS
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"
    ubtu22cis_ask_passwd_to_boot: false
    ubtu22cis_rule_1_1_1_1: true
    ubtu22cis_bootloader_password_hash: "grub.pbkdf2.sha512.changethispassword" 
  tasks:
   - name: Add user to docker group
     user:
       name: '{{ansible_env.SUDO_USER}}'
       groups: docker
       append: yes
     when: ansible_env.SUDO_USER != 'root'

