---
- hosts: all
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - Ubuntu22CIS
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"
    ubtu22cis_time_sync_tool: ntp

