---
- hosts: all
  gather_facts: no
  become: no
  roles:
    - Ubuntu22CIS
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"
  tasks:
   - name: Add user to docker group
     user:
       name: '{{ansible_env.SUDO_USER}}'
       groups: docker
       append: yes
     when: ansible_env.SUDO_USER != 'root'

