# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

---
- hosts: all
  gather_facts: no
  tasks:
    - name: touch
      raw: touch /tmp/ansible-raw-test
    - name: raw test
      raw: date
    - name: command test
      command: echo "the command module"