# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0
---
- hosts: all
  gather_facts: no
  pre_tasks:
    - name: install python
      raw: 'cat < sripts/pre-work.sh'
      args:
        executable: /bin/bash
  tasks:
    - name: command test
      vars:
        ansible_python_interpreter: /usr/bin/env python3
      command: echo "the command module"