name: Ubuntu (22.04) Packer Build
on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_SG_ID: ${{ secrets.AWS_SG_ID }}
  PACKER_TEMPLATE: base-ami.pkr.hcl

jobs:
  packer-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Add Ansible Repo
        run: sudo apt-add-repository ppa:ansible/ansible -y
      - name: Install Deps
        run: sudo apt update && sudo apt install -y ansible awscli
      - name: Get Github action IP
        run: echo "ACTION_IP=$(curl -s checkip.amazonaws.com)" >> $GITHUB_ENV
      - name: Add Github Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress \
          --group-id $AWS_SG_ID \
          --protocol tcp --port 22 \
          --cidr $ACTION_IP/32
      - name: Remove Github Actions IP from the Security Group
        if: always()
        run: |
          aws ec2 revoke-security-group-ingress \
          --group-id $AWS_SG_ID \
          --protocol tcp --port 22 \
          --cidr $ACTION_IP/32
      - name: Setup packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PACKER_VERSION }}
      - name: Packer Init
        id: init
        run: packer init ${{ env.PACKER_TEMPLATE }}
      - name: Packer Validate
        id: validate
        run: packer validate -var-file=/tmp/packer-var.json ${{ env.PACKER_TEMPLATE }} 2>&1 | tee ${BUILD_LOG}
      - name: Packer Build
        run: packer build -color=false -on-error=abort -var-file=/tmp/packer-var.json ${{ env.PACKER_TEMPLATE }} 2>&1 | tee ${BUILD_LOG}