name: Ubuntu (22.04) Packer Build
on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_SG_ID: ${{ secrets.AWS_SG_ID }}

jobs:
  packer-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Add Ansible Repo
        run: sudo apt-add-repository ppa:ansible/ansible -y
      - name: Install Deps
        run: sudo apt update && sudo apt install -y ansible awscli
      - name: Get Github action IP
        run: echo "ACTION_IP=$(curl -s checkip.amazonaws.com)" >> $GITHUB_ENV
      - name: Add Github Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress \
          --group-id $AWS_SG_ID \
          --protocol tcp --port 22 \
          --cidr $ACTION_IP/32
      - name: Remove Github Actions IP from the Security Group
        if: always()
        run: |
          aws ec2 revoke-security-group-ingress \
          --group-id $AWS_SG_ID \
          --protocol tcp --port 22 \
          --cidr $ACTION_IP/32